import React from 'react';
import type { Metadata } from 'next';
import '@/app/globals.css';
import Footer from '@/components/layout/Footer';
import { footerMenuList } from '@/data/footerMenu';

export const metadata: Metadata = {
  title: 'vijob-clone-coding',
  description: 'Generated by create next app',
  icons: {
    icon: 'data:;base64,iVBORw0KGgo='
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="ko">
      <body>
        <div className="flex flex-row justify-center w-full h-full bg-black">
          <div className="flex flex-col justify-center w-full max-w-[430px] max-[860px]:max-w-full bg-primary-bg">
            <div className="flex-grow overflow-y-auto">
              <div className="flex flex-col relative w-full h-full overflow-y-auto">{children}</div>
            </div>
            <Footer footerMenuList={footerMenuList} />
          </div>
        </div>
      </body>
    </html>
  );
}
