import React from 'react';
import type { Metadata } from 'next';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: 'data:;base64,iVBORw0KGgo='
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="ko">
      <body>
        <div className="flex flex-row justify-center w-full h-full bg-black">
          <div className="flex flex-col justify-center w-full max-w-[430px] max-[860px]:max-w-full bg-primary-bg">
            <main className="flex-grow overflow-y-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
